# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('village', models.CharField(max_length=20)),
                ('crop', models.CharField(max_length=20)),
                ('sdate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('fertiliser', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('quantity_unit', models.CharField(choices=[('TON', 'ton'), ('KG', 'kilogram'), ('G', 'gram'), ('L', 'litre'), ('ML', 'mililitre')], max_length=3)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.FarmDetail')),
            ],
        ),
        migrations.AddField(
            model_name='farmdetail',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.FarmerDetail'),
        ),
    ]
