# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmdetail',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='scheduledata',
            name='farm',
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='crop',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='fertiliser',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='quantity_unit',
            field=models.CharField(choices=[('TON', 'ton'), ('KG', 'kilogram'), ('G', 'gram'), ('L', 'litre'), ('ML', 'mililitre')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='sdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='village',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FarmDetail',
        ),
        migrations.DeleteModel(
            name='ScheduleData',
        ),
    ]
