# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowingdate', models.DateField(default=datetime.date.today)),
                ('days', models.IntegerField()),
                ('fertiliser', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('quantity_unit', models.CharField(choices=[('TON', 'ton'), ('KG', 'kilogram'), ('G', 'gram'), ('L', 'litre'), ('ML', 'mililitre')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduledata',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='farmdetail',
            name='sdate',
        ),
        migrations.AlterField(
            model_name='farmdetail',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='ScheduleData',
        ),
        migrations.AddField(
            model_name='scheduledetail',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.FarmDetail'),
        ),
    ]
