# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0002_auto_20180518_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerdetail',
            old_name='sdate',
            new_name='sowingdate',
        ),
    ]
