# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_auto_20180518_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowingdate', models.DateField(default=datetime.date.today)),
                ('days', models.IntegerField()),
                ('fertiliser', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('quantity_unit', models.CharField(choices=[('TON', 'ton'), ('KG', 'kilogram'), ('G', 'gram'), ('L', 'litre'), ('ML', 'mililitre')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmerdetail',
            name='days',
        ),
        migrations.RemoveField(
            model_name='farmerdetail',
            name='fertiliser',
        ),
        migrations.RemoveField(
            model_name='farmerdetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='farmerdetail',
            name='quantity_unit',
        ),
        migrations.RemoveField(
            model_name='farmerdetail',
            name='sowingdate',
        ),
        migrations.AddField(
            model_name='scheduledetail',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.FarmerDetail'),
        ),
    ]
