# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0004_auto_20180518_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(default=0)),
                ('village', models.CharField(max_length=20)),
                ('crop', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmerdetail',
            name='area',
        ),
        migrations.RemoveField(
            model_name='farmerdetail',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='farmerdetail',
            name='village',
        ),
        migrations.AlterField(
            model_name='scheduledetail',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.FarmDetail'),
        ),
        migrations.AddField(
            model_name='farmdetail',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.FarmerDetail'),
        ),
    ]
