# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0006_auto_20180519_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmdetail',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.FarmerDetail'),
        ),
    ]
